
name: CI

on:
  push:
    branches:    
      - master
    tags-ignore:
      - *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependecies
        run: python3.8 -m pip install -r requirements.txt

      - name: Build the Ansible collection
        run: |
          mkdir -p build
          ansible-galaxy collection build -f --output-path build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: mrsuicideparrot-proxmox_plugin.tar.gz
          path: build/mrsuicideparrot-proxmox_plugin-*.tar.gz   